// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxinhLmbgI-2xhkc9Kc_rU68l5abKwgU',
    appId: '1:57969242539:web:8c1f1c197b92c0a39de2ee',
    messagingSenderId: '57969242539',
    projectId: 'push-notification-e6ab5',
    authDomain: 'push-notification-e6ab5.firebaseapp.com',
    storageBucket: 'push-notification-e6ab5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhIlXpJh4MyYRCqciRIQilARecu2C9o4',
    appId: '1:57969242539:android:b08072a1d2ba2a959de2ee',
    messagingSenderId: '57969242539',
    projectId: 'push-notification-e6ab5',
    storageBucket: 'push-notification-e6ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIvsOcwWce0EvJ-2Wr45iLC_AVvtSTfzg',
    appId: '1:57969242539:ios:7a5929919eed8d1d9de2ee',
    messagingSenderId: '57969242539',
    projectId: 'push-notification-e6ab5',
    storageBucket: 'push-notification-e6ab5.firebasestorage.app',
    iosBundleId: 'com.example.blocTutorial',
  );
}
